-- Window function syntax
-- WINDOW_FUNCTION() OVER(PARTITION BY COLUMN1 ORDER BY COLUMN2) 

-- ROW_NUMBER()

-- TOP 2 EMPLOYEES from each depratment

SELECT * FROM(
    SELECT
    EMPLOYEED_ID,
    EMPLOYEE_NAME,
    DEPARTMENT,
    CITY,
    SALARY,
    ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) AS ROW_NUM
    FROM EMPLOYEES
) WHERE ROW_NUM <= 2;


WITH EMP_CTE AS (
    SELECT
    EMPLOYEED_ID,
    EMPLOYEE_NAME,
    DEPARTMENT,
    CITY,
    SALARY,
    ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) AS ROW_NUM
    FROM EMPLOYEES
)
SELECT * FROM EMP_CTE WHERE ROW_NUM <= 2;


-- TOP SELLING PRODUCTS

WITH PRODUCT_AGG AS (
    SELECT
    PRODUCT_CATEGORY_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY,
    sum(ORDER_ITEM_SUBTOTAL) AS TOTAL_AMOUNT,
    FROM(
        SELECT
        O.ORDER_ITEM_ORDER_ID AS ORDER_ID,
        O.ORDER_ITEM_ID,
        O.ORDER_ITEM_PRODUCT_ID AS PRODUCT_ID,
        O.ORDER_ITEM_QUANTITY,
        O.ORDER_ITEM_SUBTOTAL,
        P.PRODUCT_CATEGORY_ID,
        P.PRODUCT_NAMEFROM ORDER_ITEMS O
        JOIN PRODUCT P 
        ON P.ORDER_ITEM_PRODUCT_ID = P.PRODUCT_ID
    ) GROUP BY PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY_ID
 )
WINDOWED_CTE AS (
    SELECT *,
    ROW_NUMBER() OVER(PARTITION BY PRODUCT_CATEGORY_ID ORDER BY TOTAL_AMOUNT)) AS ROW_NUM FROM PRODUCT_AGG
)
SELECT* FROM WINDOWED_CTE WHERE ROW_NUM <= 1;


-- TWO PEOPLE WITH SAME SALARY

SELECT *,
ROW_NUMBER() OVER(ORDER BY SALARY) AS ROW_NUM,
RANK() OVER(ORDER BY SALARY) AS RNK,
DENSE_RANK() OVR(ORDER BY SALARY) AS DNS_RNK 
FROM EMPLOYEES;


-- DAY BT DAY SALE

SELECT
SALE_DATE,
PRODUCT_ID,
PRODUCT_NAME,
UNITS_SOLD AS CURRENT_SALE,
LEAD(UNITS_SOLD,1,0) OVER(PARTITION BY PRODUCT_ID ORDER BY SALE_DATE) AS NEXT_DAY_SALE,
LAG(UNITS_SOLD,1,0) OVER(PARTITION BY PRODUCT_ID ORDER BY SALE_DATE) AS PREV_DAY_SALE
FROM SALES;


--CALCULATE % OF TOTAL FOLLOWERS GAINS FOR EACH MONTH
WITH FIRST_PART AS
(
    SELECT USER_ID,
    USER_NAME,
    MONTH,
    (LINKEDIN_FOLLOWERS + FACEBOOK_FOLLOWERS + INSTAGRAM_FOLLOWERS + YOUTUBE_FOLLOWERS) AS TOTAL_FOLLOWERS
)
SECOND_PART AS (
    SELECT *,
    LEAD(TOTAL_FOLLOWERS) OVER(PARTITION BY USER_ID ORDER BY MONTH) AS NEXT_MONTH_FOLLOWERS,
    LAG(TOTAL_FOLLOWERS) OVER(PARTITION BY USER_ID ORDER BY MONTH) AS PREV_MONTH_FOLLOWERS
    FROM FIRST_PART
)
SELECT *,
ROUND((TOTAL_FOLLOWERS-PREV_MONTH_FOLLOWERS)*100/PREV_MONTH_FOLLOWERS, 2) A FOLLOWERS_GAIN
FROM SECOND_PART;